In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("/content/Bengaluru_House_Data.csv")
data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00


In [3]:
data.drop(columns=['area_type','availability','society'],inplace=True)

In [4]:
data

,location,size,total_sqft,bath,balcony,price
0,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Kothanur,2 BHK,1200,2.0,1.0,51.00
...,...,...,...,...,...,...
13315,Whitefield,5 Bedroom,3453,4.0,0.0,231.00
13316,Richards Town,4 BHK,3600,5.0,NaN,400.00
13317,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00
13318,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00


In [5]:
data.isnull().sum()

,0
location,1
size,16
total_sqft,0
bath,73
balcony,609
price,0


In [6]:
data.dropna(inplace =True)

In [7]:
data

,location,size,total_sqft,bath,balcony,price
0,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Kothanur,2 BHK,1200,2.0,1.0,51.00
...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715,3.0,3.0,112.00
13315,Whitefield,5 Bedroom,3453,4.0,0.0,231.00
13317,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00
13318,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00


In [8]:
data['location'] = data['location'].apply(lambda x: x.strip())

In [9]:
data.location.value_counts()

,count
location,
Whitefield,515
Sarjapur Road,372
Electronic City,302
Kanakpura Road,261
Thanisandra,234
...,...
Mango Garden Layout,1
CHIKKATIRUPATHI,1
Jaladarsini Layout,1


In [10]:
location_stats = data.groupby('location')['location'].agg("count").sort_values(ascending=False)

In [11]:
location_stats

,location
location,
Whitefield,515
Sarjapur Road,372
Electronic City,302
Kanakpura Road,261
Thanisandra,234
...,...
mvj engineering college,1
manyata tech park,1
manyata,1


In [12]:
location_less_than_10_enteries = location_stats[location_stats <= 10]

In [13]:
location_less_than_10_enteries

,location
location,
Basapura,10
Gunjur Palya,10
Dairy Circle,10
HAL 2nd Stage,10
Kalkere,10
...,...
mvj engineering college,1
manyata tech park,1
manyata,1


In [14]:
data['location'] = data['location'].apply(lambda x: 'other' if x in location_less_than_10_enteries else x)

In [15]:
data.location.value_counts()

,count
location,
other,2739
Whitefield,515
Sarjapur Road,372
Electronic City,302
Kanakpura Road,261
...,...
Marsur,11
Karuna Nagar,11
Prithvi Layout,11


In [16]:
data

,location,size,total_sqft,bath,balcony,price
0,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Kothanur,2 BHK,1200,2.0,1.0,51.00
...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715,3.0,3.0,112.00
13315,Whitefield,5 Bedroom,3453,4.0,0.0,231.00
13317,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00
13318,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00


In [17]:
data['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '3 Bedroom', '1 BHK', '1 RK',
       '4 BHK', '1 Bedroom', '2 Bedroom', '6 Bedroom', '8 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '11 Bedroom', '43 Bedroom',
       '14 BHK', '8 BHK', '12 Bedroom', '10 Bedroom', '13 BHK'],
      dtype=object)

In [18]:
data['bedrooms'] = data['size'].apply(lambda x: int(x.split(' ')[0]))

In [19]:
data

,location,size,total_sqft,bath,balcony,price,bedrooms
0,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07,2
1,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00,4
2,Uttarahalli,3 BHK,1440,2.0,3.0,62.00,3
3,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00,3
4,Kothanur,2 BHK,1200,2.0,1.0,51.00,2
...,...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715,3.0,3.0,112.00,3
13315,Whitefield,5 Bedroom,3453,4.0,0.0,231.00,5
13317,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00,2
13318,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00,4


In [20]:
data['total_sqft'].unique()


array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [21]:
def clean(sqft):
  tokens = sqft.split('-')
  if len(tokens) == 2:
    return(float(tokens[0])+float(tokens[1]))/2
  else:
      try:
        return float(sqft)
      except:
        return None

In [22]:
data['total_sqft'] = data['total_sqft'].apply(clean)

In [23]:
data['total_sqft'].unique()

array([1056. , 2600. , 1440. , ..., 1258.5,  774. , 4689. ])

In [24]:
data.describe()

,total_sqft,bath,balcony,price,bedrooms
count,12668.000000,12710.000000,12710.000000,12710.000000,12710.000000
mean,1511.835167,2.617309,1.584343,106.060778,2.737136
std,1162.097276,1.226000,0.817287,131.766089,1.205097
min,5.000000,1.000000,0.000000,8.000000,1.000000
25%,1100.000000,2.000000,1.000000,49.030000,2.000000
50%,1260.000000,2.000000,2.000000,70.000000,3.000000
75%,1640.000000,3.000000,2.000000,115.000000,3.000000
max,52272.000000,40.000000,3.000000,2912.000000,43.000000


In [25]:
data.dropna(inplace=True)

In [26]:
data

,location,size,total_sqft,bath,balcony,price,bedrooms
0,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4
2,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3
3,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3
4,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2
...,...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715.0,3.0,3.0,112.00,3
13315,Whitefield,5 Bedroom,3453.0,4.0,0.0,231.00,5
13317,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,1.0,60.00,2
13318,Padmanabhanagar,4 BHK,4689.0,4.0,1.0,488.00,4


In [27]:
data['sqft_per_bed'] = data['total_sqft']/data['bedrooms']

In [28]:
data

,location,size,total_sqft,bath,balcony,price,bedrooms,sqft_per_bed
0,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2,528.000000
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4,650.000000
2,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3,480.000000
3,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3,507.000000
4,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2,600.000000
...,...,...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715.0,3.0,3.0,112.00,3,571.666667
13315,Whitefield,5 Bedroom,3453.0,4.0,0.0,231.00,5,690.600000
13317,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,1.0,60.00,2,570.500000
13318,Padmanabhanagar,4 BHK,4689.0,4.0,1.0,488.00,4,1172.250000


In [29]:
data.sqft_per_bed.describe()

,sqft_per_bed
count,12668.000000
mean,570.060291
std,380.298999
min,0.714286
25%,473.333333
50%,550.000000
75%,622.500000
max,26136.000000


In [30]:
data2 = data[data['sqft_per_bed'] >= 300]

In [31]:
data2

,location,size,total_sqft,bath,balcony,price,bedrooms,sqft_per_bed
0,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2,528.000000
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4,650.000000
2,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3,480.000000
3,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3,507.000000
4,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2,600.000000
...,...,...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715.0,3.0,3.0,112.00,3,571.666667
13315,Whitefield,5 Bedroom,3453.0,4.0,0.0,231.00,5,690.600000
13317,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,1.0,60.00,2,570.500000
13318,Padmanabhanagar,4 BHK,4689.0,4.0,1.0,488.00,4,1172.250000


In [32]:
data2['price_per_sqft'] = data2['price'] * 100000 / data2['total_sqft']

/tmp/ipykernel_1342/3011775641.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['price_per_sqft'] = data2['price'] * 100000 / data2['total_sqft']


In [33]:
data2

,location,size,total_sqft,bath,balcony,price,bedrooms,sqft_per_bed,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2,528.000000,3699.810606
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4,650.000000,4615.384615
2,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3,480.000000,4305.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3,507.000000,6245.890861
4,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2,600.000000,4250.000000
...,...,...,...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715.0,3.0,3.0,112.00,3,571.666667,6530.612245
13315,Whitefield,5 Bedroom,3453.0,4.0,0.0,231.00,5,690.600000,6689.834926
13317,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,1.0,60.00,2,570.500000,5258.545136
13318,Padmanabhanagar,4 BHK,4689.0,4.0,1.0,488.00,4,1172.250000,10407.336319


In [34]:
data2.price_per_sqft.describe()

,price_per_sqft
count,12013.000000
mean,6206.082347
std,3985.518807
min,267.829813
25%,4199.363057
50%,5252.525253
75%,6823.529412
max,176470.588235


In [35]:
data3 = data2[data2['price_per_sqft'] >= 2000]

In [36]:
data3

,location,size,total_sqft,bath,balcony,price,bedrooms,sqft_per_bed,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2,528.000000,3699.810606
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4,650.000000,4615.384615
2,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3,480.000000,4305.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3,507.000000,6245.890861
4,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2,600.000000,4250.000000
...,...,...,...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715.0,3.0,3.0,112.00,3,571.666667,6530.612245
13315,Whitefield,5 Bedroom,3453.0,4.0,0.0,231.00,5,690.600000,6689.834926
13317,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,1.0,60.00,2,570.500000,5258.545136
13318,Padmanabhanagar,4 BHK,4689.0,4.0,1.0,488.00,4,1172.250000,10407.336319


In [37]:
data3.drop(columns=['size','sqft_per_bed','price_per_sqft'],axis=1, inplace=True)

/tmp/ipykernel_1342/497289224.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data3.drop(columns=['size','sqft_per_bed','price_per_sqft'],axis=1, inplace=True)


In [38]:
data3

,location,total_sqft,bath,balcony,price,bedrooms
0,Electronic City Phase II,1056.0,2.0,1.0,39.07,2
1,Chikka Tirupathi,2600.0,5.0,3.0,120.00,4
2,Uttarahalli,1440.0,2.0,3.0,62.00,3
3,Lingadheeranahalli,1521.0,3.0,1.0,95.00,3
4,Kothanur,1200.0,2.0,1.0,51.00,2
...,...,...,...,...,...,...
13314,Green Glen Layout,1715.0,3.0,3.0,112.00,3
13315,Whitefield,3453.0,4.0,0.0,231.00,5
13317,Raja Rajeshwari Nagar,1141.0,2.0,1.0,60.00,2
13318,Padmanabhanagar,4689.0,4.0,1.0,488.00,4


In [39]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer

In [40]:
col_trans = make_column_transformer((OneHotEncoder(sparse_output=False), ['location']), remainder = 'passthrough')

In [41]:
col_trans

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(sparse_output=False),
                                 ['location'])])

In [42]:
lr = LinearRegression()

In [43]:
scaler = StandardScaler()

In [44]:
model = make_pipeline(col_trans, scaler, lr)

In [45]:
## data is split into input data and output data

In [46]:
data_input = data3.drop(columns=['price'])
data_output = data3['price']

In [47]:
X_train, X_test, y_train, y_test = train_test_split(data_input, data_output, test_size=0.2, random_state=0)

In [48]:
model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning: 
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(


Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [67]:
model.score(X_test, y_test)

0.6406769060564397

In [65]:
input = pd.DataFrame([['Whitefield',	1500.0,	2.0,	2.0, 2]],columns = ['location','total_sqft','bath','balcony','bedrooms'])

In [66]:
model.predict(input)

array([90.55868852])

In [52]:
import pickle as pk

In [53]:
pk.dump(model, open('House_predicition_model.pkl', 'wb'))

In [54]:
data3.to_csv('cleaned_data.csv')

In [68]:
data_output = np.log(data3['price'])

In [70]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

In [71]:
model = make_pipeline(col_trans, RandomForestRegressor(n_estimators=100, random_state=0))

In [72]:
data3 = data3[data3['price'] <= data3['price'].quantile(0.99)]

In [73]:
data3['price_per_sqft'] = data3['price'] * 100000 / data3['total_sqft']

/tmp/ipykernel_1342/2342015064.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data3['price_per_sqft'] = data3['price'] * 100000 / data3['total_sqft']


In [74]:
data3

,location,total_sqft,bath,balcony,price,bedrooms,price_per_sqft
0,Electronic City Phase II,1056.0,2.0,1.0,39.07,2,3699.810606
1,Chikka Tirupathi,2600.0,5.0,3.0,120.00,4,4615.384615
2,Uttarahalli,1440.0,2.0,3.0,62.00,3,4305.555556
3,Lingadheeranahalli,1521.0,3.0,1.0,95.00,3,6245.890861
4,Kothanur,1200.0,2.0,1.0,51.00,2,4250.000000
...,...,...,...,...,...,...,...
13314,Green Glen Layout,1715.0,3.0,3.0,112.00,3,6530.612245
13315,Whitefield,3453.0,4.0,0.0,231.00,5,6689.834926
13317,Raja Rajeshwari Nagar,1141.0,2.0,1.0,60.00,2,5258.545136
13318,Padmanabhanagar,4689.0,4.0,1.0,488.00,4,10407.336319


In [76]:
def remove_outliers_per_location(df):
    cleaned = []
    for loc, group in df.groupby('location'):
        q1, q3 = group['price_per_sqft'].quantile([0.25, 0.75])
        iqr = q3 - q1
        filtered = group[(group['price_per_sqft'] >= q1 - 1.5*iqr) &
                         (group['price_per_sqft'] <= q3 + 1.5*iqr)]
        cleaned.append(filtered)
    return pd.concat(cleaned)

In [77]:
data3 = remove_outliers_per_location(data3)

In [78]:
data3

,location,total_sqft,bath,balcony,price,bedrooms,price_per_sqft
210,1st Block Jayanagar,2850.0,4.0,1.0,428.00,4,15017.543860
848,1st Block Jayanagar,1630.0,3.0,2.0,194.00,3,11901.840491
2152,1st Block Jayanagar,1875.0,2.0,3.0,235.00,3,12533.333333
2355,1st Block Jayanagar,2400.0,4.0,2.0,450.00,4,18750.000000
7138,1st Block Jayanagar,1200.0,2.0,0.0,130.00,3,10833.333333
...,...,...,...,...,...,...,...
13278,other,1256.0,2.0,1.0,65.00,2,5175.159236
13285,other,1353.0,2.0,2.0,110.00,2,8130.081301
13291,other,812.0,1.0,0.0,26.00,1,3201.970443
13292,other,1440.0,2.0,2.0,63.93,3,4439.583333


In [79]:
model = make_pipeline(col_trans, GradientBoostingRegressor(n_estimators=200, random_state=0))

X_train, X_test, y_train, y_test = train_test_split(data_input, data_output, test_size=0.2, random_state=0)
model.fit(X_train, y_train)
print("Score:", model.score(X_test, y_test))

Score: 0.7711085896833869


In [80]:
predicted_price = np.exp(model.predict(input))

In [81]:
model.score(X_test, y_test)

0.7711085896833869

In [82]:
model.predict(input)

array([4.37872605])

In [90]:
input = pd.DataFrame([['Electronic City Phase II',	1056.0,	2.0,	1.0,	39.07,	2,	3699.810606]],columns = ['location',	'total_sqft',	'bath',	'balcony',	'price',	'bedrooms',	'price_per_sqft'])

In [91]:
model.predict(input)

array([3.59795727])